name: Dryrun Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Target Branch
        required: true 
        default: 'release/1.1.0'

      version:
        description: Version
        required: true

      prerelease:
        description: Pre-Release
        required: false
        default: true
        type: boolean

      draft:
        description: Draft Release (do not publish)
        required: false
        default: true
        type: boolean

jobs:

  dryrelease:
    name: Tag and release dry
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SPACEKIT_RELEASE_TOKEN }}
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Changelog Entry
        id: changelog
        run: |
          CHANGELOG="$(scripts/get_changelog)"
          echo "CHANGELOG<<EOF" >> "${GITHUB_OUTPUT}"
          echo "$CHANGELOG" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"

      - name: Create GitHub release (triggers publish-to-pypi workflow)
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SPACEKIT_RELEASE_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.CHANGELOG }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: ${{ env.CHANGELOG }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
