name: Tag and release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Target Branch
        required: true 
        default: 'main'

      version:
        description: Version
        required: true

      prerelease:
        description: Pre-Release
        required: false
        type: boolean
        default: false

      draft:
        description: Draft Release (do not publish)
        required: false
        type: boolean
        default: false

jobs:

  release:
    name: Tag and release
    runs-on: ubuntu-latest

    steps:
      - name: Changelog Entry
        id: changelog
        run: echo "DESC=$(scripts/get_changelog)" >> $GITHUB_OUTPUT

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SPACEKIT_RELEASE_TOKEN }}
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --local user.name ${{ secrets.GH_USERNAME }}
          git config --local user.email ${{ secrets.GH_EMAIL }}

      - name: Set changelog release date
        if: ${{ !github.event.inputs.prerelease }}
        run:
          scripts/set_release_date ${{ github.event.inputs.version }}

      - name: Commit changelog and tag release
        if: ${{ !github.event.inputs.prerelease }}
        run: |
          git add CHANGES.rst
          git commit -m "Set ${{ github.event.inputs.version }} release date"
          git push origin HEAD
          git tag -a ${{ github.event.inputs.version }} -m "release version ${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.version }}
      
      - name: Tag Pre-release
        if: ${{ github.event.inputs.prerelease }}
        run: |
          git tag -a ${{ github.event.inputs.version }} -m "prerelease ${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.ref }} --tags

      - name: Create GitHub release (triggers publish-to-pypi workflow)
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SPACEKIT_RELEASE_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.DESC }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: ${{ env.CHANGELOG }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
